### ISSUE TITLE
Add connection types

### ISSUE THREAD

**Issue by TheRealZago** [TheRealZago/TRW-Issues#32]
_From fire219_

- [x] ~~RTC battery header~~ tbd
- [x] internal power (header)
- [x] eMMC header
- [x] CIF/CCIR656 camera header
- [x] MIPI camera header
- [x] Pi-compatible GPIO bus
- [x] touchscreen digitizer header
- [x] 3.5mm audio
- [x] audio headers (i need SPDIF, but might want to add others)
- [x] external power (barrel jack)
- [x] eDP display header
- [x] DSI display header

**Comment by TheRealZago** [comment]
I will handle RTC battery in a different way, as I need to be able to specify CR2032, NiCd barrel and such...

**Comment by fire219** [comment]
> I will handle RTC battery in a different way, as I need to be able to specify CR2032, NiCd barrel and such...

To be clear on this, I was talking about a pin header for connecting an external/separate RTC battery. Though obviously onboard batteries also need handling...

**Comment by TheRealZago** [comment]
Some older AT/XT style boards use a pin header for plugging in an external battery pack, so this will apply on a more generic scale

**Comment by TheRealZago** [comment]
Done, only RTC battery is left
