### ISSUE TITLE
Show error on entry of non existent CPU socket

### ISSUE THREAD

**Issue by drninkeo** [TheRealZago/TRW-Issues#34]
Normally when you enter a valid CPU socket into the motherboard editor, it shows you the amount of sockets and then allows you to add supported CPUs into the motherboard entry.

However, if an invalid socket is entered (for example, Socket 478 instead of mPGA478), the editor polls forever and never returns a result. What should happen instead is a message indicating that no socket of that type exists.

**Comment by TheRealZago** [comment]
That's odd, I swear it highlighted the textbox in red, but welp, guess it doesn't now

**Comment by drninkeo** [comment]
> That's odd, I swear it highlighted the textbox in red, but welp, guess it doesn't now

For me it never has nor did I know it was supposed to show an error, it always would get stuck here with the flashing orb (see below example)
![image](https://user-images.githubusercontent.com/14227565/132086556-ae9928c4-6d4e-4faa-9a44-5295034e314c.png)

**Comment by TheRealZago** [comment]
It didn't mark the field as invalid due to a wrong HTML element ID. The idea was there, though...

Done in dev, will be fixed on next update
