### ISSUE TITLE
Review list should show date that hardware was created

### ISSUE THREAD

**Issue by drninkeo** [TheRealZago/TRW-Issues#35]
Currently the hardware review list only shows the board name, the author and links to performing actions on said hardware. To help reviewers it should also say what the creation date was on the hardware, to work through any backlog of boards.

![image](https://user-images.githubusercontent.com/14227565/132086486-9fabb07d-927d-4f90-8151-fe243b632eec.png)

**Comment by TheRealZago** [comment]
Done in dev, will be uploaded in the next update
